[env:stm32f103c6t6]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube

; 强制目标芯片为 C6T6
board_build.mcu = stm32f103c6t6
board_build.f_cpu = 72000000L

upload_protocol = stlink
debug_tool = stlink

build_flags =
  -D USE_HAL_DRIVER
  -D STM32F103x6
  -D PCD_DEBUG_LEVEL=0
  -I include
